config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  filter :locale
  
  get '/sitemap' => "initiatives#sitemap", :as => :sitemap
  
  resources :initiatives, except: [:create] do
    resources :contributions, controller: 'initiatives/contributions', except: [:create, :edit, :destroy]
    resources :gateways, controller: 'initiatives/gateways', except: [:show, :destroy] do
      member do
        put :use_sandbox
        put :use_production
        put :revert_to_draft
      end
    end
    member do
      put :publish
      put :revert_to_draft
      put :update_states_from_gateways
    end
    collection do
      get :sitemap
      get '/:scope' => 'initiatives#index', as: :scoped, constraints: { scope: /most_funded|more_contributions|recently_updated/ }
    end
  end

  root "initiatives#home"

  get "/my_contributions" => "users#my_contributions", as: :my_contributions
  get "/my_initiatives" => "users#my_initiatives", as: :my_initiatives
  
  get "/:id" => "initiatives#show", as: :initiative_by_permalink

end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
  
  belongs_to :user
  has_many :contributions
  has_many :gateways

  translates :name, :first_text, :second_text

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates_presence_of :user, :currency, :minimum_value
  validates :minimum_value, numericality: { only_integer: true, greater_than: 0 }, allow_blank: true
  validates_uniqueness_of :permalink, allow_nil: true
  # Permalink cannot be a number, so it can't be confused with the id
  validates_format_of :permalink, :with => /[^\d]+/, allow_nil: true
  before_save do
    self.name = self.user.name if self.user && !self.name.present?
    self.permalink = self.permalink.gsub(/[^0-9a-z]/i, '').downcase if self.permalink
  end
  
  state_machine initial: :draft do

    state :draft
    state :published

    event :publish do
      transition :draft => :published, :if => :ready_for_publishing?
    end

    event :revert_to_draft do
      transition :published => :draft
    end

  end

  scope :most_funded, -> { with_state(:published).order("(SELECT coalesce(sum(value), 0) FROM contributions INNER JOIN gateways ON contributions.gateway_id = gateways.id WHERE contributions.initiative_id = initiatives.id AND contributions.state = 'active' AND contributions.gateway_state = gateways.state) DESC, updated_at DESC") }

  scope :more_contributions, -> { with_state(:published).order("(SELECT coalesce(count(*), 0) FROM contributions INNER JOIN gateways ON contributions.gateway_id = gateways.id WHERE contributions.initiative_id = initiatives.id AND contributions.state = 'active' AND contributions.gateway_state = gateways.state) DESC, updated_at DESC") }

  scope :recently_updated, -> { with_state(:published).order("updated_at DESC") }

  def self.not_in(*args)
    ids = args.flatten.map(&:id)
    where("id NOT IN (?)", ids)
  end

  unlock_auto_html_for :first_text, :second_text

  def to_param
    (self.permalink && self.permalink.parameterize) || (self.name && "#{self.id}-#{self.name.parameterize}") || self.id
  end

  def can_contribute?
    self.permalink.present? && self.gateways.without_state(:draft).exists? 
  end

  def ready_for_publishing?
    self.permalink.present? && self.gateways.with_state(:production).exists? 
  end

  def update_states_from_gateways!
    self.contributions.not_pending.each do |contribution|
      contribution.update_state_from_gateway!
    end
  end

  def available_gateways
    module_names = self.gateways.map(&:module_name)
    Gateway.available_gateways.select do |gateway|
      !module_names.include?(gateway.module_name)
    end
  end

end

app/controllers/initiatives/contributions_controller.rb
class Initiatives::ContributionsController < ApplicationController

  before_action :set_initiative
  before_action :set_contribution, only: %i[update show]

  respond_to :html, except: [:update]
  respond_to :json, only: [:index, :update, :show]

  after_action :verify_authorized, except: %i[index]
  after_action :verify_policy_scoped, only: %i[index]
  before_action :authenticate_user!, only: %i[new]

  def index
    @contributions = policy_scope(Contribution).where(initiative: @initiative).visible
    # This will instantiate UserDecorator for the users
    @users = @contributions.map &:user
    respond_with @contributions
  end
  
  def new    
    @contribution = @initiative.contributions.new
    @gateways = @initiative.gateways.without_state(:draft).ordered
    @contribution.gateway = @gateways.first
    @contribution.user = current_user
    authorize @contribution
    respond_with @contribution
  end
  
  def update
    authorize @contribution
    @contribution.update(contribution_params)
    respond_with @contribution, location: -> { initiative_path(@initiative.id) }
  end

  def show
    authorize @contribution
    @user = @contribution.user
    respond_with @contribution
  end

  private

  def set_initiative
    @initiative = Initiative.find(params[:initiative_id])
  end

  def set_contribution
    @contribution = @initiative.contributions.find(params[:id])
  end

  def contribution_params
    params.require(:contribution).permit(*policy(@contribution || Contribution.new).permitted_attributes)
  end

end

app/controllers/initiatives/gateways_controller.rb
class Initiatives::GatewaysController < StateController

  before_action :set_initiative
  before_action :set_gateway, except: %i[index new create]

  respond_to :html

  after_action :verify_authorized, except: %i[index]
  after_action :verify_policy_scoped, only: %i[index]

  def index
    @gateways = policy_scope(Gateway).where(initiative: @initiative)
  end

  def new
    @gateway = @initiative.gateways.new
    authorize @gateway
    module_names = @initiative.gateways.map(&:module_name)
    @gateways = @initiative.available_gateways
    respond_with @gateway
  end

  def create
    @gateway = @initiative.gateways.new(gateway_params)
    @gateways = @initiative.available_gateways
    authorize @gateway
    @gateway.save
    respond_with @gateway, location: -> { initiative_gateways_path(@initiative.id) }
  end

  def edit
    authorize @gateway
    @gateway.disable_fallback
  end

  def update
    authorize @gateway
    @gateway.update(gateway_params)
    respond_with @gateway, location: -> { initiative_gateways_path(@initiative.id) }
  end

  def use_production
    transition_state(:use_production)
  end

  def use_sandbox
    transition_state(:use_sandbox)
  end

  def revert_to_draft
    transition_state(:revert_to_draft)
  end

  private

  def set_initiative
    @initiative = Initiative.find(params[:initiative_id])
  end

  def set_gateway
    @gateway = @initiative.gateways.find(params[:id])
  end

  def gateway_params
    params.require(:gateway).permit(*policy(@gateway || Gateway.new).permitted_attributes)
  end

  def transition_state(transition)
    super(@gateway, transition, initiative_gateways_path(@initiative.id))
  end

  def allow_default_locales?
    set_initiative
    policy(@initiative).update?
  end

end

app/controllers/initiatives_controller.rb
class InitiativesController < StateController
  
  before_action :set_initiative, except: %i[index new sitemap home]

  respond_to :html, except: [:sitemap]
  respond_to :xml, only: [:sitemap]
  respond_to :json, only: [:update, :show]

  after_action :verify_authorized, except: %i[home index sitemap]
  after_action :verify_policy_scoped, only: %i[home index sitemap]
  before_action :authenticate_user!, only: %i[new]

  has_scope :most_funded, type: :boolean
  has_scope :more_contributions, type: :boolean
  has_scope :recently_updated, type: :boolean
  before_action :set_scope, only: %i[index]

  def home
    @initiatives = policy_scope(Initiative).with_state(:published)
    @most_funded = @initiatives.most_funded.limit(3)
    @more_contributions = @initiatives.more_contributions.not_in(@most_funded).limit(3)
    @recently_updated = @initiatives.recently_updated.not_in(@most_funded, @more_contributions).limit(3)
    respond_with @initiatives
  end

  def index
    @initiatives = apply_scopes(policy_scope(Initiative).with_state(:published))
    respond_with @initiatives
  end

  def show
    authorize @initiative
    unless request.path.match(/\A\/#{params[:locale]}\/#{@initiative.to_param}(\.\w+)?\z/)
      format = request.format.symbol
      return redirect_to initiative_by_permalink_path("#{@initiative.to_param}#{".#{format}" unless format == :html}")
    end
    respond_with @initiative
  end

  def new
    @initiative = Initiative.new
    authorize @initiative
    @initiative.user = current_user
    resource_name = @initiative.class.model_name.human
    if @initiative.save
      flash[:notice] = t('flash.actions.create.notice', resource_name: resource_name)
      redirect_to initiative_by_permalink_path(@initiative)
    else
      flash[:alert] = t('flash.actions.create.alert', resource_name: resource_name)
      redirect_to :root
    end
  end

  def edit
    authorize @initiative
    @initiative.disable_fallback
  end

  def update
    authorize @initiative
    @initiative.update(initiative_params)
    respond_with @initiative
  end

  def destroy
    authorize @initiative
    @initiative.destroy
    respond_with @initiative
  end

  def sitemap
    @initiatives = policy_scope(Initiative).home_page
    respond_with @initiatives
  end

  def publish
    transition_state(@initiative, :publish)
  end

  def revert_to_draft
    transition_state(@initiative, :revert_to_draft)
  end

  def update_states_from_gateways
    authorize @initiative
    @initiative.update_states_from_gateways!
    flash[:notice] = t('flash.actions.update.notice', resource_name: @initiative.class.model_name.human)
    respond_with @initiative
  end

  private

  def initiative_params
    params.require(:initiative).permit(*policy(@initiative || Initiative.new).permitted_attributes)
  end

  def set_initiative
    @initiative ||= Initiative.find_by_permalink(params[:id])
    @initiative ||= Initiative.find(params[:id])
  end

  def set_scope
    return unless params[:scope]
    params[params[:scope].to_sym] = true
  end

  def allow_default_locales?
    return false unless params[:id]
    set_initiative
    policy(@initiative).update?
  end

end

app/helpers/initiatives/contributions_helper.rb
module Initiatives::ContributionsHelper
  def can_manage_contribution? contribution
    policy(contribution.initiative).update? || policy(contribution).update?
  end
end

app/views/initiatives/_initiative.html.slim
article.initiative
  a href=initiative_by_permalink_path(initiative) title=initiative.name
    .image= image_tag(initiative.image.url(:medium)) if initiative.image.present?
    .status
      h5
        span.currency= initiative.display_currency
        span.number= initiative.total_value
        div= Initiative.human_attribute_name(:total_value).downcase
      h5
        span.number= initiative.total_contributions
        div
          - words = Initiative.human_attribute_name(:total_contributions).downcase.split(' ')
          = words[0].pluralize(initiative.total_contributions)
          = " #{words[1]}".pluralize(initiative.total_contributions)
    .info
      h3= truncate initiative.name, length: 48
      h4= truncate strip_tags(initiative.first_text_html), length: 140
      - if current_user && current_user.admin?
        h4= mail_to initiative.user.email, "Por #{initiative.user.name}"

app/views/initiatives/_inititative.html.slim
article.initiative
  a href=initiative_path(initiative) title=initiative.name
    .info
      h3= truncate initiative.name, length: 48
      h4= truncate initiative.first_text, length: 48

app/views/initiatives/edit.html.slim
- suppress_headline_and_article!
- content_for :title do
  = "#{t('devise.registrations.edit.title', resource: nil)} #{@initiative.name}"
article
  h2== "#{t('devise.registrations.edit.title', resource: nil)} #{link_to @initiative.name, initiative_by_permalink_path(@initiative)}"
  = form_for @initiative, url: initiative_path(@initiative.id) do |form|
    = render partial: 'error_explanation', locals: { resource: @initiative }
    = form.label :image
    = form.file_field :image
    = flag_list 32 do
        = flag(locale_country(I18n.locale, true), :title => t("languages.#{I18n.locale}"))
    = form.label :name
    = form.text_field :name, value: @initiative.name
    = flag_list 32 do
        = flag(locale_country(I18n.locale, true), :title => t("languages.#{I18n.locale}"))
    = form.label :first_text
    = form.text_area :first_text, value: @initiative.first_text, class: 'has_em'
    em== t('.textile')
    = flag_list 32 do
        = flag(locale_country(I18n.locale, true), :title => t("languages.#{I18n.locale}"))
    = form.label :second_text
    = form.text_area :second_text, value: @initiative.second_text, class: 'has_em'
    em== t('.textile')
    = form.label :permalink
    = form.text_field :permalink, class: 'has_em'
    em== t('.permalink')
    = form.label :currency
    = form.select :currency, Money::Currency.table.keys.map{ |key| ["#{Money::Currency.table[key][:name]} (#{Money::Currency.table[key][:symbol]})", key.to_s.upcase] }.sort, {}, { class: "has_em" }
    em== t('.currency')
    = form.label :minimum_value
    = form.text_field :minimum_value, class: 'money'
    .submit= form.submit t('helpers.submit.submit', model: nil)

app/views/initiatives/home.html.slim
- suppress_headline_and_article!
- suppress_logo!
- content_for :title do
  = t('.title')
- content_for :url do
  = root_url
- content_for :header do
  = link_to :root do
    h1= image_tag 'logo.png', alt: "Unlock", title: "Unlock"
  h2= t('.h2')
  h3= t('.h3')
  section.new= link_to t('helpers.submit.create', model: nil), new_initiative_path, class: 'button'
- content_for :post_header do
  ul
    li
      = image_tag "no_fee.png"
      h2= t('.no_fee.h2')
      h3= t('.no_fee.h3')
    li
      = image_tag "not_curated.png"
      h2= t('.not_curated.h2')
      h3= t('.not_curated.h3')
- content_for :meta_tags do
  meta name="description" content=t('.description')
  meta name="keywords" content="unlock #{t('.keywords')}"
  meta property="og:title" content="#{t('.title')} · Unlock"
  meta property="og:type" content="website"
  meta property="og:url" content=(root_url)
  meta property="og:image" content=="#{request.protocol}#{request.host_with_port}#{image_path("logo_facebook.png")}"
  meta property="og:description" content=t('.description')
  meta name="author" content="Larusso + Weinmann"
section.text
  h2= t('.text.h2')
  h3= t('.text.h3')
- if @most_funded.exists?
  .section_title
    h4= t('.most_funded')
    = link_to t('view_all'), scoped_initiatives_path(:most_funded)
  section.most_funded= render @most_funded
- if @more_contributions.exists?
  .section_title
    h4= t('.more_contributions')
    = link_to t('view_all'), scoped_initiatives_path(:more_contributions)
  section.more_contributions= render @more_contributions
- if @recently_updated.exists?
  .section_title
    h4= t('.recently_updated')
    = link_to t('view_all'), scoped_initiatives_path(:recently_updated)
  section.recently_updated= render @recently_updated

app/views/initiatives/index.html.slim
- content_for :title do
  - if params[:scope].present?
    = t(".scoped.#{params[:scope]}")
  - else
    = t('.title')
- if @initiatives.exists?
  section.initiatives= render @initiatives

app/views/initiatives/show.html.slim
- suppress_headline_and_article!
- content_for :title do
  == strip_tags(@initiative.name)
- content_for :meta_tags do
  meta name="description" content=strip_tags(@initiative.first_text_html)
  meta name="keywords" content=strip_tags(@initiative.first_text_html)
  meta property="og:title" content=@initiative.name
  meta property="og:type" content="website"
  meta property="og:url" content=initiative_by_permalink_url(@initiative)
  meta property="og:image" content=(@initiative.image.present? ? @initiative.image.url : "#{request.protocol}#{request.host_with_port}#{image_path("logo_facebook.png")}")
  meta property="og:description" content=strip_tags(@initiative.first_text_html)
  meta name="author" content=@initiative.user.name
- content_for :pre_header do
  .image
    - if @initiative.image.present?
      = link_to image_tag(@initiative.image.url, style: "margin-top: #{@initiative.margin}"), @initiative.image.url, target: :_blank
- content_for :header do
  h1= @initiative.name
  - if @initiative.first_text.present?
    section.first_text= @initiative.first_text_html
- content_for :post_header do
  section.status
    h2
      span.currency= @initiative.display_currency
      span.number= @initiative.total_value
      div= Initiative.human_attribute_name(:total_value).downcase
    h2
      span.number= @initiative.total_contributions
      div
        - words = Initiative.human_attribute_name(:total_contributions).downcase.split(' ')
        = words[0].pluralize(@initiative.total_contributions)
        = " "
        = link_to words[1].pluralize(@initiative.total_contributions), initiative_contributions_path(@initiative.id)
article id=dom_id(@initiative) data-url=initiative_path(@initiative.id)
  - if @initiative.can_contribute?
    section.contribute
      a.button href=new_initiative_contribution_path(@initiative.id)
        = t('contribute')
  - if @initiative.second_text.present?
    section.second_text= @initiative.second_text_html
    - if @initiative.second_text.length > 400 && @initiative.can_contribute?
      section.contribute
        a.button href=new_initiative_contribution_path(@initiative.id)
          = t('contribute')
  - if policy(@initiative).update?
    section.actions
      .action= link_to t('devise.registrations.edit.title', resource: nil), edit_initiative_path(@initiative.id), class: 'button'
      .action= link_to Gateway.model_name.human.pluralize, initiative_gateways_path(@initiative.id), class: 'button'
      - if @initiative.can_publish?
        .action= link_to t('activerecord.state_machines.initiative.state.events.publish'), publish_initiative_path(@initiative.id), method: :put, data: { confirm: t('confirm') }, class: 'button'
      - if @initiative.can_revert_to_draft?
        .action= link_to t('activerecord.state_machines.initiative.state.events.revert_to_draft'), revert_to_draft_initiative_path(@initiative.id), method: :put, data: { confirm: t('confirm') }, class: 'button'
      - if policy(@initiative).destroy?
        .action= link_to t('destroy'), initiative_path(@initiative.id), method: :delete, data: { confirm: t('confirm') }, class: "button careful"