config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  filter :locale
  
  get '/sitemap' => "initiatives#sitemap", :as => :sitemap
  
  resources :initiatives, except: [:create] do
    resources :contributions, controller: 'initiatives/contributions', except: [:create, :edit, :destroy]
    resources :gateways, controller: 'initiatives/gateways', except: [:show, :destroy] do
      member do
        put :use_sandbox
        put :use_production
        put :revert_to_draft
      end
    end
    member do
      put :publish
      put :revert_to_draft
      put :update_states_from_gateways
    end
    collection do
      get :sitemap
      get '/:scope' => 'initiatives#index', as: :scoped, constraints: { scope: /most_funded|more_contributions|recently_updated/ }
    end
  end

  root "initiatives#home"

  get "/my_contributions" => "users#my_contributions", as: :my_contributions
  get "/my_initiatives" => "users#my_initiatives", as: :my_initiatives
  
  get "/:id" => "initiatives#show", as: :initiative_by_permalink

end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :initiative
  belongs_to :gateway
  store_accessor :gateway_data

  validates_presence_of :user, :initiative, :gateway, :value
  validates :value, numericality: { only_integer: true, greater_than_or_equal_to: :minimum_value }, allow_blank: true

  accepts_nested_attributes_for :user
  
  after_initialize :include_gateway_module

  def self.visible
    with_state(:active).joins(:gateway).where("gateways.state = contributions.gateway_state").order("updated_at DESC")
  end
  
  def self.not_pending
    without_state(:pending).joins(:initiative).joins(:gateway).where("gateways.state = contributions.gateway_state").order("updated_at DESC")
  end
  
  state_machine initial: :pending do

    state :pending
    state :active
    state :suspended

    event :activate do
      transition [:pending, :suspended] => :active
    end

    event :suspend do
      transition :active => :suspended
    end

  end

  def minimum_value
    self.initiative.try(:minimum_value) || 0
  end

  private
  
  def include_gateway_module
    return unless self.gateway && module_name = self.gateway.module_name
    class_eval do
      include "#{module_name}::Models::Contribution".constantize
    end
  end

end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
  
  belongs_to :user
  has_many :contributions
  has_many :gateways

  translates :name, :first_text, :second_text

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates_presence_of :user, :currency, :minimum_value
  validates :minimum_value, numericality: { only_integer: true, greater_than: 0 }, allow_blank: true
  validates_uniqueness_of :permalink, allow_nil: true
  # Permalink cannot be a number, so it can't be confused with the id
  validates_format_of :permalink, :with => /[^\d]+/, allow_nil: true
  before_save do
    self.name = self.user.name if self.user && !self.name.present?
    self.permalink = self.permalink.gsub(/[^0-9a-z]/i, '').downcase if self.permalink
  end
  
  state_machine initial: :draft do

    state :draft
    state :published

    event :publish do
      transition :draft => :published, :if => :ready_for_publishing?
    end

    event :revert_to_draft do
      transition :published => :draft
    end

  end

  scope :most_funded, -> { with_state(:published).order("(SELECT coalesce(sum(value), 0) FROM contributions INNER JOIN gateways ON contributions.gateway_id = gateways.id WHERE contributions.initiative_id = initiatives.id AND contributions.state = 'active' AND contributions.gateway_state = gateways.state) DESC, updated_at DESC") }

  scope :more_contributions, -> { with_state(:published).order("(SELECT coalesce(count(*), 0) FROM contributions INNER JOIN gateways ON contributions.gateway_id = gateways.id WHERE contributions.initiative_id = initiatives.id AND contributions.state = 'active' AND contributions.gateway_state = gateways.state) DESC, updated_at DESC") }

  scope :recently_updated, -> { with_state(:published).order("updated_at DESC") }

  def self.not_in(*args)
    ids = args.flatten.map(&:id)
    where("id NOT IN (?)", ids)
  end

  unlock_auto_html_for :first_text, :second_text

  def to_param
    (self.permalink && self.permalink.parameterize) || (self.name && "#{self.id}-#{self.name.parameterize}") || self.id
  end

  def can_contribute?
    self.permalink.present? && self.gateways.without_state(:draft).exists? 
  end

  def ready_for_publishing?
    self.permalink.present? && self.gateways.with_state(:production).exists? 
  end

  def update_states_from_gateways!
    self.contributions.not_pending.each do |contribution|
      contribution.update_state_from_gateway!
    end
  end

  def available_gateways
    module_names = self.gateways.map(&:module_name)
    Gateway.available_gateways.select do |gateway|
      !module_names.include?(gateway.module_name)
    end
  end

end

app/controllers/initiatives/contributions_controller.rb
class Initiatives::ContributionsController < ApplicationController

  before_action :set_initiative
  before_action :set_contribution, only: %i[update show]

  respond_to :html, except: [:update]
  respond_to :json, only: [:index, :update, :show]

  after_action :verify_authorized, except: %i[index]
  after_action :verify_policy_scoped, only: %i[index]
  before_action :authenticate_user!, only: %i[new]

  def index
    @contributions = policy_scope(Contribution).where(initiative: @initiative).visible
    # This will instantiate UserDecorator for the users
    @users = @contributions.map &:user
    respond_with @contributions
  end
  
  def new    
    @contribution = @initiative.contributions.new
    @gateways = @initiative.gateways.without_state(:draft).ordered
    @contribution.gateway = @gateways.first
    @contribution.user = current_user
    authorize @contribution
    respond_with @contribution
  end
  
  def update
    authorize @contribution
    @contribution.update(contribution_params)
    respond_with @contribution, location: -> { initiative_path(@initiative.id) }
  end

  def show
    authorize @contribution
    @user = @contribution.user
    respond_with @contribution
  end

  private

  def set_initiative
    @initiative = Initiative.find(params[:initiative_id])
  end

  def set_contribution
    @contribution = @initiative.contributions.find(params[:id])
  end

  def contribution_params
    params.require(:contribution).permit(*policy(@contribution || Contribution.new).permitted_attributes)
  end

end

app/controllers/initiatives/gateways_controller.rb
class Initiatives::GatewaysController < StateController

  before_action :set_initiative
  before_action :set_gateway, except: %i[index new create]

  respond_to :html

  after_action :verify_authorized, except: %i[index]
  after_action :verify_policy_scoped, only: %i[index]

  def index
    @gateways = policy_scope(Gateway).where(initiative: @initiative)
  end

  def new
    @gateway = @initiative.gateways.new
    authorize @gateway
    module_names = @initiative.gateways.map(&:module_name)
    @gateways = @initiative.available_gateways
    respond_with @gateway
  end

  def create
    @gateway = @initiative.gateways.new(gateway_params)
    @gateways = @initiative.available_gateways
    authorize @gateway
    @gateway.save
    respond_with @gateway, location: -> { initiative_gateways_path(@initiative.id) }
  end

  def edit
    authorize @gateway
    @gateway.disable_fallback
  end

  def update
    authorize @gateway
    @gateway.update(gateway_params)
    respond_with @gateway, location: -> { initiative_gateways_path(@initiative.id) }
  end

  def use_production
    transition_state(:use_production)
  end

  def use_sandbox
    transition_state(:use_sandbox)
  end

  def revert_to_draft
    transition_state(:revert_to_draft)
  end

  private

  def set_initiative
    @initiative = Initiative.find(params[:initiative_id])
  end

  def set_gateway
    @gateway = @initiative.gateways.find(params[:id])
  end

  def gateway_params
    params.require(:gateway).permit(*policy(@gateway || Gateway.new).permitted_attributes)
  end

  def transition_state(transition)
    super(@gateway, transition, initiative_gateways_path(@initiative.id))
  end

  def allow_default_locales?
    set_initiative
    policy(@initiative).update?
  end

end

app/controllers/initiatives_controller.rb
class InitiativesController < StateController
  
  before_action :set_initiative, except: %i[index new sitemap home]

  respond_to :html, except: [:sitemap]
  respond_to :xml, only: [:sitemap]
  respond_to :json, only: [:update, :show]

  after_action :verify_authorized, except: %i[home index sitemap]
  after_action :verify_policy_scoped, only: %i[home index sitemap]
  before_action :authenticate_user!, only: %i[new]

  has_scope :most_funded, type: :boolean
  has_scope :more_contributions, type: :boolean
  has_scope :recently_updated, type: :boolean
  before_action :set_scope, only: %i[index]

  def home
    @initiatives = policy_scope(Initiative).with_state(:published)
    @most_funded = @initiatives.most_funded.limit(3)
    @more_contributions = @initiatives.more_contributions.not_in(@most_funded).limit(3)
    @recently_updated = @initiatives.recently_updated.not_in(@most_funded, @more_contributions).limit(3)
    respond_with @initiatives
  end

  def index
    @initiatives = apply_scopes(policy_scope(Initiative).with_state(:published))
    respond_with @initiatives
  end

  def show
    authorize @initiative
    unless request.path.match(/\A\/#{params[:locale]}\/#{@initiative.to_param}(\.\w+)?\z/)
      format = request.format.symbol
      return redirect_to initiative_by_permalink_path("#{@initiative.to_param}#{".#{format}" unless format == :html}")
    end
    respond_with @initiative
  end

  def new
    @initiative = Initiative.new
    authorize @initiative
    @initiative.user = current_user
    resource_name = @initiative.class.model_name.human
    if @initiative.save
      flash[:notice] = t('flash.actions.create.notice', resource_name: resource_name)
      redirect_to initiative_by_permalink_path(@initiative)
    else
      flash[:alert] = t('flash.actions.create.alert', resource_name: resource_name)
      redirect_to :root
    end
  end

  def edit
    authorize @initiative
    @initiative.disable_fallback
  end

  def update
    authorize @initiative
    @initiative.update(initiative_params)
    respond_with @initiative
  end

  def destroy
    authorize @initiative
    @initiative.destroy
    respond_with @initiative
  end

  def sitemap
    @initiatives = policy_scope(Initiative).home_page
    respond_with @initiatives
  end

  def publish
    transition_state(@initiative, :publish)
  end

  def revert_to_draft
    transition_state(@initiative, :revert_to_draft)
  end

  def update_states_from_gateways
    authorize @initiative
    @initiative.update_states_from_gateways!
    flash[:notice] = t('flash.actions.update.notice', resource_name: @initiative.class.model_name.human)
    respond_with @initiative
  end

  private

  def initiative_params
    params.require(:initiative).permit(*policy(@initiative || Initiative.new).permitted_attributes)
  end

  def set_initiative
    @initiative ||= Initiative.find_by_permalink(params[:id])
    @initiative ||= Initiative.find(params[:id])
  end

  def set_scope
    return unless params[:scope]
    params[params[:scope].to_sym] = true
  end

  def allow_default_locales?
    return false unless params[:id]
    set_initiative
    policy(@initiative).update?
  end

end

app/helpers/initiatives/contributions_helper.rb
module Initiatives::ContributionsHelper
  def can_manage_contribution? contribution
    policy(contribution.initiative).update? || policy(contribution).update?
  end
end

app/views/initiatives/contributions/_base_form.html.slim
= form.hidden_field :user_id
= form.hidden_field :initiative_id
= form.hidden_field :gateway_id, value: gateway.id
h3= t('.value')
= form.label :value, "#{Contribution.human_attribute_name(:value)} (#{gateway.initiative.display_currency(true)})"
= form.text_field :value, class: "has_em money"
em== t('.info', link: link_to(gateway.name, gateway.url, target: :_blank))

app/views/initiatives/contributions/_contribution.html.slim
li.contribution
  = link_to initiative_contribution_path(contribution.initiative.id, contribution) do
    .image
      - if contribution.hide_name?
        = image_tag('user.svg')
      - else
        = contribution.user.display_image
    .info
      h4 
        - if contribution.hide_name?
          = Contribution.human_attribute_name(:hide_name?)
        - else
          = truncate contribution.user.display_name, length: 40
      - unless contribution.hide_value? && !policy(contribution.initiative).update?
        h5= contribution.display_value
      em #{time_ago_in_words(contribution.created_at)}

app/views/initiatives/contributions/_sandbox_warning.html.slim
- if gateway.sandbox?
  .warning
    h3= t('.title', gateway: gateway.name)
    ul
      li= t('.items.first')
      li= t('.items.second')

app/views/initiatives/contributions/index.html.slim
- suppress_headline_and_article!
- content_for :title do
  = "#{Contribution.model_name.human.pluralize} #{t('to')} #{@initiative.name}"
article
  h2== "#{Contribution.model_name.human.pluralize} #{t('to')} #{link_to @initiative.name, initiative_by_permalink_path(@initiative)}"
  - if @contributions.exists?
    ul.contributions= render @contributions
  - else
    em= t('empty', model: Contribution.model_name.human.downcase)

app/views/initiatives/contributions/new.html.slim
- suppress_headline_and_article!
- content_for :title do
  = "#{t('contribute_to')} #{@initiative.name}"
article
  h2== "#{t('contribute_to')} #{link_to @initiative.name, initiative_by_permalink_path(@initiative)}"
  = render partial: 'error_explanation', locals: { resource: @contribution }
  - if(first_gateway = @gateways.first) && @gateways.size == 1
    = render partial: "/#{first_gateway.module_name.underscore}/contributions/form", locals: { gateway: first_gateway }
  - else
    ul.accordion
      - if current_user.module_name.present?
        - expanded = current_user.module_name
      - else
        - expanded = first_gateway.module_name
      - @gateways.each do |gateway|
        li class=('expanded' if gateway.module_name == expanded)
          h4= gateway.display_title
          .content= render partial: "/#{gateway.module_name.underscore}/contributions/form", locals: { gateway: gateway }

app/views/initiatives/contributions/show.html.slim
- suppress_headline_and_article!
- content_for :title do
  - if policy(@contribution).update? && @contribution.created_at > 2.days.ago
    = t('.thank_you', initiative: @initiative.name)
  - else
    = "#{Contribution.model_name.human} #{t('to')} #{@initiative.name}"
article
  h2
    - if policy(@contribution).update? && @contribution.created_at > 2.days.ago
      == t('.thank_you', initiative: link_to(@initiative.name, initiative_by_permalink_path(@initiative)))
    - else
      == "#{Contribution.model_name.human} #{t('to')} #{link_to @initiative.name, initiative_by_permalink_path(@initiative)}"
  .contribution
    .image
      - if @contribution.hide_name? && !policy(@initiative).update? && !policy(@contribution).update?
        = image_tag('user.svg')
      - else
        = @contribution.user.display_image
    .info
      h4 
        - if @contribution.hide_name? && !policy(@initiative).update? && !policy(@contribution).update?
          = Contribution.human_attribute_name(:hide_name?)
        - elsif policy(@initiative).update?
          = mail_to @contribution.user.email, @contribution.user.display_name
        - else
          = @contribution.user.display_name
      - unless @contribution.hide_value? && !policy(@initiative).update? && !policy(@contribution).update?
        h5= @contribution.display_value
      em== t('.summary', created_at: l(@contribution.created_at, format: :short), sandbox: ("<strong>#{t('activerecord.state_machines.gateway.state.states.sandbox').downcase}</strong> " if @contribution.gateway_state == 'sandbox'), gateway: @contribution.gateway.name)
      - if policy(@contribution).update?
        .options id=dom_id(@contribution) data-url=initiative_contribution_path(@contribution.initiative.id, @contribution.id)
          .field
            = check_box_tag :"hide_name_#{@contribution.id}", "1", @contribution.hide_name, :class => "editable", :"data-attribute" => "hide_name", :"data-formtype" => "checkbox"
            = label_tag :"hide_name_#{@contribution.id}", Contribution.human_attribute_name(:hide_name)
          .field
            = check_box_tag :"hide_value_#{@contribution.id}", "1", @contribution.hide_value, :class => "editable", :"data-attribute" => "hide_value", :"data-formtype" => "checkbox"
            = label_tag :"hide_value_#{@contribution.id}", Contribution.human_attribute_name(:hide_value)
  - if policy(@contribution).update?
    .gateway_data class=(@contribution.active? ? 'success' : ('failure' if @contribution.suspended?))
      h4= "#{@contribution.class.model_name.human} #{@contribution.human_state_name.downcase}"
      ul
        li== t('.gateway_identifier', gateway_identifier: @contribution.gateway_identifier)
        li== t('.payments', link: link_to(@contribution.gateway.name, @contribution.gateway.url, target: :_blank))
        li== t('.suspend')
        li== t('.next_invoice', date: @contribution.next_invoice_date)
      .links
        - if @contribution.can_activate?
          = link_to t('activerecord.state_machines.contribution.state.events.activate'), "/#{I18n.locale}#{@contribution.gateway.path}/#{@contribution.id}/activate", method: :put, class: "button"
        - if @contribution.can_suspend?
          = link_to t('activerecord.state_machines.contribution.state.events.suspend'), "/#{I18n.locale}#{@contribution.gateway.path}/#{@contribution.id}/suspend", method: :put, class: "button suspend"